const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

// H-3 companion. Expo's default manifest ships android:allowBackup="true",
// which hands the whole app-private directory — muthoy.db included — to
// Android Auto Backup (Google Drive) and to device-to-device transfer.
//
// That is a plaintext exfiltration path today. It becomes something worse
// once H-3 lands: the SQLCipher key is wrapped by a non-exportable
// AndroidKeyStore key that does NOT travel with a backup, so a restored
// device would receive ciphertext it can never open. Silent, total,
// unrecoverable data loss that looks like a successful restore.
//
// The database is device-bound by design; the shop's durable copy is the
// server (H-11). So backup is turned off rather than filtered.
//
// Lives as a config plugin because android/ is gitignored and regenerated by
// prebuild — a hand edit to the generated manifest would not survive.

const DATA_EXTRACTION_RULES_RESOURCE = 'data_extraction_rules';
const FULL_BACKUP_CONTENT_RESOURCE = 'backup_rules';

// Some Android 12+ device-transfer implementations still consult these rules
// when allowBackup="false". MMKV stores named instances below files/mmkv (not
// SharedPreferences), so exclude that complete directory including its CRC
// companions, current/future stores, auth tokens, sessions, device identity,
// and sync cursors.
const DATA_EXTRACTION_RULES = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidBackupProtection.js (H-3). Do not edit. -->
<data-extraction-rules>
  <cloud-backup>
    <exclude domain="database" />
    <exclude domain="file" path="SQLite" />
    <exclude domain="file" path="mmkv/" />
    <exclude domain="sharedpref" path="muthoy_db_key_v1.xml" />
  </cloud-backup>
  <device-transfer>
    <exclude domain="database" />
    <exclude domain="file" path="SQLite" />
    <exclude domain="file" path="mmkv/" />
    <exclude domain="sharedpref" path="muthoy_db_key_v1.xml" />
  </device-transfer>
</data-extraction-rules>
`;

// Android 11 and below read this file instead of data-extraction-rules.
const FULL_BACKUP_CONTENT = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidBackupProtection.js (H-3). Do not edit. -->
<full-backup-content>
  <exclude domain="database" />
  <exclude domain="file" path="SQLite" />
  <exclude domain="file" path="mmkv/" />
  <exclude domain="sharedpref" path="muthoy_db_key_v1.xml" />
</full-backup-content>
`;

const withBackupDisabledManifest = (config) =>
  withAndroidManifest(config, (modConfig) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(modConfig.modResults);
    application.$['android:allowBackup'] = 'false';
    application.$['android:fullBackupContent'] = `@xml/${FULL_BACKUP_CONTENT_RESOURCE}`;
    application.$['android:dataExtractionRules'] = `@xml/${DATA_EXTRACTION_RULES_RESOURCE}`;
    return modConfig;
  });

const withBackupRuleResources = (config) =>
  withDangerousMod(config, [
    'android',
    (modConfig) => {
      const xmlDirectory = path.join(
        modConfig.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(xmlDirectory, { recursive: true });
      fs.writeFileSync(
        path.join(xmlDirectory, `${DATA_EXTRACTION_RULES_RESOURCE}.xml`),
        DATA_EXTRACTION_RULES,
        'utf8',
      );
      fs.writeFileSync(
        path.join(xmlDirectory, `${FULL_BACKUP_CONTENT_RESOURCE}.xml`),
        FULL_BACKUP_CONTENT,
        'utf8',
      );
      return modConfig;
    },
  ]);

module.exports = function withAndroidBackupProtection(config) {
  return withBackupRuleResources(withBackupDisabledManifest(config));
};
